//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoSortAssistant {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public MoveMappingData[] Mappings
        {
            get
            {
                return ((MoveMappingData[])(this["Mappings"]));
            }
            set
            {
                this["Mappings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.3G2; *.3GP2; *.3GP; *.3GPP; *.amr; *.amv; *.asf; *.avi; *.bik; *.divx; *.dpg; *.dvr-ms; *.evo; *.ifo; *.flv; *.k3g; *.m1v; *.m2v; *.m2t; *.m2ts; *.m4v; *.m4p; *.m4b; *.mkv; *.mov; *.mp4; *.mpeg; *.mpg; *.mpe; *.mpv2; *.mp2v; *.mts; *.mxf; *.nsr; *.nsv; *.ogm; *.ogv; *.rm; *.ram; *.rmvb; *.rpm; *.rv; *.qt; *.skm; *.swf; *.ts; *.tp; *.tpr; *.trp; *.vob; *.wm; *.wmp; *.wmv")]
        public string Mask {
            get {
                return ((string)(this["Mask"]));
            }
            set {
                this["Mask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App {
            get {
                return ((string)(this["App"]));
            }
            set {
                this["App"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"%1\"")]
        public string AppArgs {
            get {
                return ((string)(this["AppArgs"]));
            }
            set {
                this["AppArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Placeholder {
            get {
                return ((string)(this["Placeholder"]));
            }
            set {
                this["Placeholder"] = value;
            }
        }
    }
}
